apiVersion: apps/v1
kind: Deployment
metadata:
  name: grow-app
  labels:
    app: grow-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: grow-app
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: grow-app
    spec:
      containers:
        - name: grow-app
          image: yun1code/grow:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3001

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: grow-db-secret
                  key: DB_HOST

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: grow-db-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grow-db-secret
                  key: DB_PASSWORD

            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: grow-db-secret
                  key: DB_DATABASE

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: grow-db-secret
                  key: DB_PORT

            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: grow-db-secret
                  key: SESSION_SECRET

      imagePullSecrets:
        - name: dockerhub-secrets   # DockerHub private이면 필요 / public이면 삭제해도 됨
