apiVersion: v1
kind: Secret
metadata:
  name: grow-db-secret
  namespace: grow-dev
type: Opaque
data:
  DB_HOST: MzQuNTAuMjcuMTU0
  DB_USER: Z3Jvd191c2Vy
  DB_PASSWORD: R3JvdzEyMzQh
  DB_DATABASE: Z3Jvdw==
  DB_PORT: MzMwNg==
