apiVersion: v1
kind: Service
metadata:
  name: grow-app-service
  labels:
    app: grow-app
spec:
  type: LoadBalancer
  selector:
    app: grow-app
  ports:
    - port: 3001        # 클러스터 내부에서 접근할 포트
      targetPort: 3001  # 컨테이너 내부 포트
      protocol: TCP

